apiVersion: apps/v1
kind: Deployment
metadata:
  name: brians-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: brians-config-volume-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: brians-config-volume-1
        configMap:
          name: configmap-deployment-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brians-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: brians-config-volume-2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: brians-config-volume-2
        configMap:
          name: configmap-deployment-two
